name: smartphone_env
channels:
  - defaults
dependencies:
  - python=3.7.10
  - requests
  - beautifulsoup4
  - pandas=1.3.4
  - numpy=1.21.5
  - scikit-learn=1.0.2
  - flask
  - streamlit=1.25.0
  - selenium
  - xgboost
